export const EMERGENCY_QUICK = [
  { id: 'chest', labelKey: 'card_chest', hint: 'chest pain' },
  { id: 'breath', labelKey: 'card_breath', hint: 'cannot breathe' },
  { id: 'accident', labelKey: 'card_accident', hint: 'severe accident injury' },
  { id: 'burn', labelKey: 'card_burn', hint: 'severe burn' },
  { id: 'poison', labelKey: 'card_poison', hint: 'poisoning overdose' },
  { id: 'fever', labelKey: 'card_fever', hint: 'high fever confusion' },
];

export const I18N = {
  en: {
    nearby_facilities: 'Nearby facilities',
    hospitals_realtime_caption: 'Real-time nearby hospitals when location is allowed.',
    hospitals_fetch_error: 'Location not available. Unable to fetch hospitals.',
    hospitals_fallback_notice: 'Location unavailable. Showing hospitals for a default nearby region.',
    hospitals_load_failed: 'Could not load hospitals',
    no_facilities_found: 'No facilities found',
    check_location_and_retry: 'Check location permission and try again.',
    medical: 'medical',
    try_again: 'Try again',
    back_to_triage: 'Back to triage',
    location_prefix: 'Location',
    location_active: 'active',
    location_not_granted: 'not granted',
    telegram_delivery_failed: 'Telegram delivery failed',
    sos_triggered: 'SOS triggered',
    manual_sos: 'Manual SOS',
    incident_history_title: 'Incident history',
    history_load_error: 'Could not load history (is backend running?)',
    no_incidents: 'No server-side incidents yet.',
    profile_page_title: 'Family & emergency profile',
    profile_page_caption: 'Used for context and SOS contacts.',
    saving: 'Saving…',
    save_success: 'Saved securely for this session.',
    save_local: 'Saved locally only.',
    name_label: 'Name',
    age_label: 'Age',
    allergies_label: 'Allergies (comma separated)',
    contacts_phone_label: 'Emergency contacts (comma separated phone)',
    notes_label: 'Notes',
    save_profile: 'Save profile',
    report_title: 'Emergency report',
    report_requires_triage: 'Run triage first for a complete report.',
    generate_handoff: 'Generate handoff document',
    generating: 'Generating…',
    download_pdf: 'Download PDF',
    brand: 'Aegis AI',
    tagline: 'Smart Healthcare Communication & Emergency Response',
    need_help: 'I NEED HELP NOW',
    triage: 'Start triage',
    home: 'Home',
    continue: 'Continue',
    analyzing: 'Analyzing…',
    mic: 'Voice input',
    stop: 'Stop',
    voice_not_supported: 'Voice input not supported on this device.',
    triage_failed: 'Triage failed. Please try again.',
    triage_step_intake: 'Intake',
    triage_step_questions: 'Questions',
    triage_step_results: 'Results',
    triage_title: 'Describe symptoms',
    triage_helper_title: 'Helper mode: describe what you observe',
    triage_helper_text: 'Use clear, factual details (what happened, when it started, and what changed).',
    triage_privacy_hint: 'Avoid sharing unnecessary personal details. This tool does not diagnose or prescribe.',
    red_flag_warning: 'Red-flag wording detected. If this is happening now, use SOS or call emergency services immediately.',
    summary: 'Summary',
    intent: 'Category',
    open_sos: 'Open SOS',
    generate_report: 'Generate report',
    analyze: 'Analyze',
    followups_title: 'Quick follow-up questions',
    followups_subtitle: 'Short answers help prioritize safety.',
    sos: 'SOS',
    hospitals: 'Hospitals',
    reports: 'Reports',
    settings: 'Settings',
    settings_subtitle: 'Language, appearance, accessibility, profile, contacts, permissions, and alerts.',
    language: 'Language',
    language_help: 'Choose the UI language. Medical content remains safety-first and consistent.',
    theme: 'Theme',
    theme_help: 'Adjust appearance for different environments.',
    dark_help: 'Recommended in low-light environments.',
    care_mode_help: 'Larger text and tap targets for caregiving situations.',
    my_profile: 'My profile',
    my_profile_help: 'Keep patient details ready for faster emergency handoff.',
    edit_profile: 'Edit profile',
    view_history: 'View history',
    privacy_permissions: 'Privacy & permissions',
    privacy_permissions_help: 'Location and notifications are optional and can be changed anytime.',
    permissions_note:
      'Location is used to find nearby hospitals and add a map link to SOS. You can continue without location, but recommendations may be less precise.',
    emergency_contacts: 'Emergency contacts',
    emergency_contacts_help: 'Manage who receives SOS alerts. Add phone and Telegram IDs for fast outreach.',
    receive_sos: 'Receive SOS',
    add_contact: 'Add emergency contact',
    edit_last_contact: 'Edit most recent contact',
    full_name: 'Full name',
    relationship: 'Relationship',
    relationship_unknown: 'Relationship not set',
    phone: 'Phone number',
    primary: 'Primary',
    set_primary: 'Set as primary',
    remove: 'Remove',
    unnamed_contact: 'Unnamed contact',
    empty_contacts: 'No emergency contacts yet. Add at least one person you trust.',
    telegram_recipients: 'Telegram recipients',
    telegram_recipients_help:
      'Optional: configure Telegram chat IDs to receive server-side SOS alerts. The bot must be able to message the chat.',
    add_telegram: 'Add Telegram recipient',
    edit_last_recipient: 'Edit most recent recipient',
    unnamed_recipient: 'Unnamed recipient',
    empty_telegram: 'No Telegram recipients yet. Add chat IDs if you want instant SOS alerts in Telegram.',
    telegram_chat_id: 'Telegram chat ID',
    telegram_chat_id_required: 'Telegram chat ID required',
    telegram_valid: 'Telegram chat ID looks valid.',
    telegram_invalid: 'Invalid chat ID',
    validate: 'Validate',
    disclaimer_short:
      'Aegis does not diagnose or prescribe. In an emergency, call your local emergency number.',
    card_chest: 'Chest pain',
    card_breath: 'Breathing trouble',
    card_accident: 'Accident',
    card_burn: 'Burn',
    card_poison: 'Poisoning',
    card_fever: 'Fever',
    symptom_placeholder: 'Describe what is happening…',
    voice: 'Voice',
    send: 'Continue',
    risk_low: 'Low',
    risk_med: 'Medium',
    risk_high: 'High',
    risk_crit: 'Critical',
    why: 'Why this level?',
    first_aid: 'First aid',
    sos_center: 'SOS Control Center',
    sos_subtitle: 'One-tap emergency alert to your configured recipients.',
    sos_one_tap: 'One-tap SOS',
    sos_help_text: 'Sends patient summary, urgency, time, and location (if available).',
    sos_ready: 'Ready. Tap SOS only in a real emergency.',
    sos_sending: 'Sending emergency alert…',
    sos_sent: 'Alert sent.',
    sos_failed: 'Alert failed. Check Telegram recipients and network.',
    sos_recipients: 'Recipients',
    copy_emergency_text: 'Copy emergency text',
    open_map: 'Open map',
    share_location: 'Share live location',
    copy_report: 'Copy report',
    home_intro: 'Real-time healthcare communication, smart SOS routing, live hospital discovery, and AI-powered emergency coordination.',
    live_gps_tracking: 'Live GPS Tracking',
    ai_triage_enabled: 'AI Triage Enabled',
    realtime_alerts: 'Real-Time Alerts',
    hipaa_ready: 'HIPAA Ready',
    live_status: 'Live Command Status',
    emergency_network_online: 'Emergency Network: Online',
    risk_score: 'Risk Score',
    triage_level: 'Triage Level',
    ai_activity_feed: 'AI Activity Feed',
    ai_activity_feed_desc: 'Analyzing vitals and nearest ICU availability...',
    mini_live_map_preview: 'Mini Live Map Preview • 3 responders nearby',
    emergency_action_grid: 'Emergency Action Grid',
    quick_intake_prompts: 'Quick Intake Prompts',
    quick_intake_subtitle: 'Use one tap to start triage with a common emergency concern.',
    live_map_hospitals: 'Live Map + Hospitals',
    realtime_routes_markers: 'Real-time routes and markers',
    map_unavailable: 'Map unavailable',
    no_nearby_hospitals_loaded: 'No nearby hospitals loaded.',
    system_feed: 'System Feed',
    last_updated: 'Last updated',
    not_synced_yet: 'not synced yet',
    refreshing_location_hospitals: 'Refreshing location and hospitals...',
    location_hospital_sync_complete: 'Location and hospital sync complete.',
    no_active_emergency_timeline: 'No active emergency timeline yet. Start triage to create a live case.',
    location_status: 'Location Status',
    available: 'Available',
    pending: 'Pending',
    awaiting: 'awaiting',
    response_mode: 'Response Mode',
    bystander_mode: 'Helping Others',
    self_mode: 'Self Care',
    network: 'Network',
    online: 'Online',
    offline: 'Offline',
    stable: 'stable',
    check: 'check',
    syncing: 'syncing',
    live: 'live',
    user: 'user',
    prompt_chest_sweat: 'Chest pain and sweating',
    prompt_unconscious: 'Unconscious patient',
    prompt_breathing_difficulty: 'Severe breathing difficulty',
    prompt_heavy_bleeding: 'Heavy bleeding after accident',
    beds: 'Beds',
    eta: 'ETA',
    nearby: 'nearby',
    badge_critical: 'critical',
    badge_high: 'high',
    badge_moderate: 'moderate',
    cardiac_arrest: 'Cardiac Arrest',
    cardiac_desc: 'Immediate CPR and dispatch priority workflow.',
    breathing_issues: 'Breathing Issues',
    breathing_desc: 'Airway risk detection with rapid triage routing.',
    accident_trauma: 'Accident Trauma',
    trauma_desc: 'Multi-injury assessment and escalation protocol.',
    burn_injury: 'Burn Injury',
    burn_desc: 'Severity-guided burn emergency response.',
    poisoning_title: 'Poisoning',
    poisoning_desc: 'Toxicity response with ingestion guidance path.',
    high_fever: 'High Fever',
    high_fever_desc: 'Danger signal screening and care recommendations.',
    stroke_title: 'Stroke',
    stroke_desc: 'FAST symptom check and golden-hour coordination.',
    mental_health_crisis: 'Mental Health Crisis',
    mental_health_desc: 'Crisis-safe intervention and urgent support routing.',
    setup_checklist: 'Complete your emergency setup',
    setup_checklist_hint: 'Add profile details and at least one emergency contact to make SOS fully ready.',
    dismiss: 'Dismiss',
    report_empty_hint: 'Start triage first, then come back to generate a clinician-ready report.',
    accessibility: 'Accessibility',
    accessibility_help: 'Improve readability and interaction comfort.',
    large_text: 'Large text',
    reduce_motion: 'Reduce motion',
    high_contrast: 'High contrast',
    notification_preferences: 'Notification preferences',
    notification_preferences_help: 'Control alert behavior during emergencies.',
    quiet_mode: 'Quiet mode',
    vibration: 'Vibration',
    quick_edit: 'Quick edit newest entries',
    invalid_phone: 'Invalid phone format',
    care_mode: 'Care mode (larger UI)',
    bystander: 'I am helping someone else',
    dark: 'Dark mode',
  },
  hi: {
    nearby_facilities: 'नज़दीकी सुविधाएँ',
    hospitals_realtime_caption: 'लोकेशन अनुमति होने पर रियल-टाइम नज़दीकी अस्पताल दिखते हैं।',
    hospitals_fetch_error: 'लोकेशन उपलब्ध नहीं। अस्पताल लोड नहीं हो सके।',
    hospitals_fallback_notice: 'लोकेशन उपलब्ध नहीं है। डिफ़ॉल्ट नज़दीकी क्षेत्र के अस्पताल दिखाए जा रहे हैं।',
    hospitals_load_failed: 'अस्पताल लोड नहीं हो सके',
    no_facilities_found: 'कोई सुविधा नहीं मिली',
    check_location_and_retry: 'लोकेशन अनुमति जाँचें और फिर प्रयास करें।',
    medical: 'मेडिकल',
    try_again: 'फिर प्रयास करें',
    back_to_triage: 'ट्राइज पर वापस',
    location_prefix: 'लोकेशन',
    location_active: 'सक्रिय',
    location_not_granted: 'अनुमति नहीं',
    telegram_delivery_failed: 'Telegram डिलीवरी विफल',
    sos_triggered: 'SOS ट्रिगर किया गया',
    manual_sos: 'मैनुअल SOS',
    incident_history_title: 'घटना इतिहास',
    history_load_error: 'इतिहास लोड नहीं हो सका (क्या बैकएंड चल रहा है?)',
    no_incidents: 'अभी कोई सर्वर-साइड घटना नहीं है।',
    profile_page_title: 'परिवार और आपात प्रोफ़ाइल',
    profile_page_caption: 'कॉन्टेक्स्ट और SOS संपर्कों के लिए उपयोग होता है।',
    saving: 'सेव हो रहा है…',
    save_success: 'इस सेशन के लिए सुरक्षित रूप से सेव हुआ।',
    save_local: 'केवल लोकली सेव हुआ।',
    name_label: 'नाम',
    age_label: 'उम्र',
    allergies_label: 'एलर्जी (कॉमा से अलग)',
    contacts_phone_label: 'आपात संपर्क (फोन, कॉमा से अलग)',
    notes_label: 'नोट्स',
    save_profile: 'प्रोफ़ाइल सेव करें',
    report_title: 'आपातकालीन रिपोर्ट',
    report_requires_triage: 'पूरी रिपोर्ट के लिए पहले ट्राइज चलाएँ।',
    generate_handoff: 'हैंडऑफ़ दस्तावेज़ बनाएं',
    generating: 'बन रहा है…',
    download_pdf: 'PDF डाउनलोड',
    brand: 'Aegis AI',
    tagline: 'स्मार्ट हेल्थकेयर संचार और आपातकालीन प्रतिक्रिया',
    need_help: 'मुझे अभी मदद चाहिए',
    triage: 'ट्राइज शुरू करें',
    home: 'होम',
    continue: 'आगे',
    analyzing: 'विश्लेषण हो रहा है…',
    mic: 'वॉइस इनपुट',
    stop: 'रोकें',
    voice_not_supported: 'इस डिवाइस पर वॉइस इनपुट समर्थित नहीं है।',
    triage_failed: 'ट्राइज विफल। कृपया दोबारा प्रयास करें।',
    triage_step_intake: 'इनटेक',
    triage_step_questions: 'प्रश्न',
    triage_step_results: 'परिणाम',
    triage_title: 'लक्षण बताएं',
    triage_helper_title: 'हेल्पर मोड: जो आप देख रहे हैं वह बताएं',
    triage_helper_text: 'स्पष्ट और तथ्यात्मक विवरण दें (क्या हुआ, कब शुरू हुआ, क्या बदला)।',
    triage_privacy_hint: 'अनावश्यक व्यक्तिगत जानकारी साझा न करें। Aegis निदान या दवा निर्देश नहीं देता।',
    red_flag_warning: 'रेड-फ्लैग संकेत मिले। यदि यह अभी हो रहा है, SOS दबाएँ या स्थानीय आपात नंबर पर कॉल करें।',
    summary: 'सारांश',
    intent: 'श्रेणी',
    open_sos: 'SOS खोलें',
    generate_report: 'रिपोर्ट बनाएं',
    analyze: 'विश्लेषण करें',
    followups_title: 'त्वरित फ़ॉलो‑अप प्रश्न',
    followups_subtitle: 'छोटे जवाब सुरक्षा को प्राथमिकता देने में मदद करते हैं।',
    sos: 'एसओएस',
    hospitals: 'अस्पताल',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    settings_subtitle: 'भाषा, थीम, एक्सेसिबिलिटी, प्रोफ़ाइल, संपर्क, अनुमतियाँ और अलर्ट।',
    language: 'भाषा',
    language_help: 'ऐप की भाषा चुनें। सुरक्षा-संबंधी सामग्री हमेशा प्राथमिक रहेगी।',
    theme: 'थीम',
    theme_help: 'पर्यावरण के अनुसार UI बदलें।',
    dark_help: 'कम रोशनी में उपयोग के लिए उपयुक्त।',
    care_mode_help: 'देखभाल की स्थिति में बड़ा टेक्स्ट और बड़े टच टारगेट।',
    my_profile: 'मेरी प्रोफ़ाइल',
    my_profile_help: 'आपात स्थिति में तेजी से जानकारी साझा करने के लिए विवरण तैयार रखें।',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    view_history: 'इतिहास देखें',
    privacy_permissions: 'गोपनीयता और अनुमतियाँ',
    privacy_permissions_help: 'लोकेशन/नोटिफिकेशन वैकल्पिक हैं और कभी भी बदले जा सकते हैं।',
    permissions_note:
      'लोकेशन का उपयोग नज़दीकी अस्पताल खोजने और SOS में मैप लिंक जोड़ने के लिए होता है। लोकेशन के बिना भी इस्तेमाल कर सकते हैं, पर सुझाव कम सटीक हो सकते हैं।',
    emergency_contacts: 'आपातकालीन संपर्क',
    emergency_contacts_help: 'SOS अलर्ट किसे भेजना है यह प्रबंधित करें। फोन और Telegram ID जोड़ें।',
    receive_sos: 'SOS प्राप्त करें',
    add_contact: 'संपर्क जोड़ें',
    edit_last_contact: 'हाल का संपर्क संपादित करें',
    full_name: 'पूरा नाम',
    relationship: 'रिश्ता',
    relationship_unknown: 'रिश्ता सेट नहीं',
    phone: 'फ़ोन नंबर',
    primary: 'मुख्य',
    set_primary: 'मुख्य बनाएं',
    remove: 'हटाएं',
    unnamed_contact: 'बिना नाम का संपर्क',
    empty_contacts: 'अभी कोई संपर्क नहीं। कम-से-कम एक विश्वसनीय व्यक्ति जोड़ें।',
    telegram_recipients: 'Telegram प्राप्तकर्ता',
    telegram_recipients_help: 'वैकल्पिक: SOS संदेश Telegram पर भेजने के लिए chat IDs जोड़ें।',
    add_telegram: 'Telegram प्राप्तकर्ता जोड़ें',
    edit_last_recipient: 'हाल का प्राप्तकर्ता संपादित करें',
    unnamed_recipient: 'बिना नाम का प्राप्तकर्ता',
    empty_telegram: 'अभी कोई Telegram प्राप्तकर्ता नहीं।',
    telegram_chat_id: 'Telegram chat ID',
    telegram_chat_id_required: 'Telegram chat ID आवश्यक है',
    telegram_valid: 'Telegram chat ID सही लगता है।',
    telegram_invalid: 'अमान्य chat ID',
    validate: 'जाँचें',
    disclaimer_short:
      'Aegis निदान या दवा निर्देश नहीं देता। आपातकाल में स्थानीय आपात नंबर पर कॉल करें।',
    card_chest: 'छाती में दर्द',
    card_breath: 'सांस की तकलीफ',
    card_accident: 'दुर्घटना',
    card_burn: 'जलना',
    card_poison: 'जहर',
    card_fever: 'बुखार',
    symptom_placeholder: 'क्या हो रहा है, लिखें…',
    voice: 'आवाज़',
    send: 'आगे',
    risk_low: 'कम',
    risk_med: 'मध्यम',
    risk_high: 'उच्च',
    risk_crit: 'गंभीर',
    why: 'यह स्तर क्यों?',
    first_aid: 'प्राथमिक उपचार',
    sos_center: 'एसओएस केंद्र',
    sos_subtitle: 'आपके कॉन्फ़िगर किए गए प्राप्तकर्ताओं को एक‑टैप अलर्ट।',
    sos_one_tap: 'एक‑टैप SOS',
    sos_help_text: 'सारांश, जोखिम, समय और (यदि उपलब्ध) लोकेशन भेजता है।',
    sos_ready: 'तैयार। केवल वास्तविक आपातकाल में SOS दबाएँ।',
    sos_sending: 'अलर्ट भेजा जा रहा है…',
    sos_sent: 'अलर्ट भेज दिया गया।',
    sos_failed: 'अलर्ट विफल। Telegram प्राप्तकर्ता और नेटवर्क जाँचें।',
    sos_recipients: 'प्राप्तकर्ता',
    copy_emergency_text: 'आपात पाठ कॉपी करें',
    open_map: 'मैप खोलें',
    share_location: 'लाइव लोकेशन साझा करें',
    copy_report: 'रिपोर्ट कॉपी करें',
    home_intro: 'रियल-टाइम हेल्थकेयर कम्युनिकेशन, स्मार्ट SOS रूटिंग और लाइव अस्पताल खोज।',
    live_gps_tracking: 'लाइव GPS ट्रैकिंग',
    ai_triage_enabled: 'AI ट्रायाज सक्षम',
    realtime_alerts: 'रियल-टाइम अलर्ट',
    hipaa_ready: 'HIPAA रेडी',
    live_status: 'लाइव कमांड स्थिति',
    emergency_network_online: 'इमरजेंसी नेटवर्क: ऑनलाइन',
    risk_score: 'रिस्क स्कोर',
    triage_level: 'ट्रायाज स्तर',
    ai_activity_feed: 'AI गतिविधि फ़ीड',
    ai_activity_feed_desc: 'वाइटल्स और नजदीकी ICU उपलब्धता का विश्लेषण...',
    mini_live_map_preview: 'मिनी लाइव मैप प्रीव्यू • 3 रिस्पॉन्डर पास में',
    emergency_action_grid: 'इमरजेंसी एक्शन ग्रिड',
    quick_intake_prompts: 'त्वरित इनटेक प्रॉम्प्ट',
    quick_intake_subtitle: 'एक टैप से सामान्य इमरजेंसी के लिए ट्रायाज शुरू करें।',
    live_map_hospitals: 'लाइव मैप + अस्पताल',
    realtime_routes_markers: 'रियल-टाइम रूट्स और मार्कर्स',
    map_unavailable: 'मैप उपलब्ध नहीं',
    no_nearby_hospitals_loaded: 'नजदीकी अस्पताल लोड नहीं हुए।',
    system_feed: 'सिस्टम फ़ीड',
    last_updated: 'अंतिम अपडेट',
    not_synced_yet: 'अभी सिंक नहीं हुआ',
    refreshing_location_hospitals: 'लोकेशन और अस्पताल रीफ्रेश हो रहे हैं...',
    location_hospital_sync_complete: 'लोकेशन और अस्पताल सिंक पूरा।',
    no_active_emergency_timeline: 'कोई सक्रिय इमरजेंसी टाइमलाइन नहीं। लाइव केस के लिए ट्रायाज शुरू करें।',
    location_status: 'लोकेशन स्थिति',
    available: 'उपलब्ध',
    pending: 'प्रतीक्षारत',
    awaiting: 'इंतज़ार',
    response_mode: 'रिस्पॉन्स मोड',
    bystander_mode: 'दूसरों की मदद',
    self_mode: 'स्वयं देखभाल',
    network: 'नेटवर्क',
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    stable: 'स्थिर',
    check: 'जांचें',
    syncing: 'सिंक हो रहा',
    live: 'लाइव',
    user: 'यूज़र',
    prompt_chest_sweat: 'छाती में दर्द और पसीना',
    prompt_unconscious: 'बेहोश मरीज',
    prompt_breathing_difficulty: 'गंभीर सांस लेने में कठिनाई',
    prompt_heavy_bleeding: 'दुर्घटना के बाद भारी रक्तस्राव',
    beds: 'बेड',
    eta: 'ईटीए',
    nearby: 'पास में',
    badge_critical: 'गंभीर',
    badge_high: 'उच्च',
    badge_moderate: 'मध्यम',
    cardiac_arrest: 'कार्डियक अरेस्ट',
    cardiac_desc: 'तुरंत CPR और प्राथमिक डिस्पैच वर्कफ़्लो।',
    breathing_issues: 'सांस संबंधी समस्या',
    breathing_desc: 'एयरवे जोखिम पहचान के साथ तेज ट्रायाज रूटिंग।',
    accident_trauma: 'दुर्घटना ट्रॉमा',
    trauma_desc: 'मल्टी-इंजरी आकलन और एस्केलेशन प्रोटोकॉल।',
    burn_injury: 'जलन चोट',
    burn_desc: 'गंभीरता-आधारित बर्न इमरजेंसी प्रतिक्रिया।',
    poisoning_title: 'विषाक्तता',
    poisoning_desc: 'इंजेशन गाइडेंस के साथ टॉक्सिसिटी प्रतिक्रिया।',
    high_fever: 'उच्च बुखार',
    high_fever_desc: 'खतरे के संकेतों की स्क्रीनिंग और देखभाल सिफारिशें।',
    stroke_title: 'स्ट्रोक',
    stroke_desc: 'FAST लक्षण जांच और गोल्डन-आवर समन्वय।',
    mental_health_crisis: 'मानसिक स्वास्थ्य संकट',
    mental_health_desc: 'संकट-सुरक्षित हस्तक्षेप और तत्काल सहायता रूटिंग।',
    setup_checklist: 'अपना इमरजेंसी सेटअप पूरा करें',
    setup_checklist_hint: 'SOS को पूरी तरह तैयार करने के लिए प्रोफ़ाइल और कम-से-कम एक संपर्क जोड़ें।',
    dismiss: 'बंद करें',
    report_empty_hint: 'पहले ट्रायाज करें, फिर क्लिनिशियन-रेडी रिपोर्ट बनाएं।',
    accessibility: 'सुलभता',
    accessibility_help: 'पठनीयता और उपयोग आराम बेहतर करें।',
    large_text: 'बड़ा टेक्स्ट',
    reduce_motion: 'कम मोशन',
    high_contrast: 'हाई कॉन्ट्रास्ट',
    notification_preferences: 'सूचना प्राथमिकताएँ',
    notification_preferences_help: 'इमरजेंसी के दौरान अलर्ट व्यवहार नियंत्रित करें।',
    quiet_mode: 'शांत मोड',
    vibration: 'वाइब्रेशन',
    quick_edit: 'नवीनतम एंट्री त्वरित संपादन',
    invalid_phone: 'अमान्य फोन प्रारूप',
    care_mode: 'केयर मोड (बड़ा UI)',
    bystander: 'मैं किसी की मदद कर रहा हूँ',
    dark: 'डार्क मोड',
  },
  kn: {
    nearby_facilities: 'ಸಮೀಪದ ಸೌಲಭ್ಯಗಳು',
    hospitals_realtime_caption: 'ಸ್ಥಳ ಅನುಮತಿ ಇದ್ದರೆ ರಿಯಲ್-ಟೈಮ್ ಸಮೀಪದ ಆಸ್ಪತ್ರೆಗಳು ತೋರಿಸುತ್ತವೆ.',
    hospitals_fetch_error: 'ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ. ಆಸ್ಪತ್ರೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ.',
    hospitals_fallback_notice: 'ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ. ಡಿಫಾಲ್ಟ್ ಸಮೀಪದ ಪ್ರದೇಶದ ಆಸ್ಪತ್ರೆಗಳು ತೋರಲಾಗುತ್ತಿವೆ.',
    hospitals_load_failed: 'ಆಸ್ಪತ್ರೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ',
    no_facilities_found: 'ಯಾವುದೇ ಸೌಲಭ್ಯ ಸಿಗಲಿಲ್ಲ',
    check_location_and_retry: 'ಸ್ಥಳ ಅನುಮತಿ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    medical: 'ವೈದ್ಯಕೀಯ',
    try_again: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    back_to_triage: 'ಟ್ರಯಾಜ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    location_prefix: 'ಸ್ಥಳ',
    location_active: 'ಸಕ್ರಿಯ',
    location_not_granted: 'ಅನುಮತಿ ಇಲ್ಲ',
    telegram_delivery_failed: 'Telegram ವಿತರಣೆಯು ವಿಫಲವಾಗಿದೆ',
    sos_triggered: 'SOS ಪ್ರಾರಂಭಿಸಲಾಗಿದೆ',
    manual_sos: 'ಮ್ಯಾನುಯಲ್ SOS',
    incident_history_title: 'ಘಟನೆ ಇತಿಹಾಸ',
    history_load_error: 'ಇತಿಹಾಸ ಲೋಡ್ ಆಗಲಿಲ್ಲ (ಬ್ಯಾಕೆಂಡ್ ಚಾಲನೆಯಲ್ಲಿದೆಯೇ?)',
    no_incidents: 'ಇನ್ನೂ ಸರ್ವರ್-ಸೈಡ್ ಘಟನೆಗಳಿಲ್ಲ.',
    profile_page_title: 'ಕುಟುಂಬ & ತುರ್ತು ಪ್ರೊಫೈಲ್',
    profile_page_caption: 'ಕಾಂಟೆಕ್ಸ್ಟ್ ಮತ್ತು SOS ಸಂಪರ್ಕಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ.',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ…',
    save_success: 'ಈ ಸೆಷನ್‌ಗೆ ಸುರಕ್ಷಿತವಾಗಿ ಉಳಿಸಲಾಗಿದೆ.',
    save_local: 'ಸ್ಥಳೀಯವಾಗಿ ಮಾತ್ರ ಉಳಿಸಲಾಗಿದೆ.',
    name_label: 'ಹೆಸರು',
    age_label: 'ವಯಸ್ಸು',
    allergies_label: 'ಅಲರ್ಜಿ (ಕಾಮಾ ಮೂಲಕ)',
    contacts_phone_label: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು (ಫೋನ್, ಕಾಮಾ ಮೂಲಕ)',
    notes_label: 'ಟಿಪ್ಪಣಿಗಳು',
    save_profile: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
    report_title: 'ತುರ್ತು ವರದಿ',
    report_requires_triage: 'ಪೂರ್ಣ ವರದಿಗೆ ಮೊದಲು ಟ್ರಯಾಜ್ ಚಾಲನೆ ಮಾಡಿ.',
    generate_handoff: 'ಹ್ಯಾಂಡಾಫ್ ದಾಖಲೆ ಸೃಷ್ಟಿಸಿ',
    generating: 'ಸೃಷ್ಟಿಸಲಾಗುತ್ತಿದೆ…',
    download_pdf: 'PDF ಡೌನ್‌ಲೋಡ್',
    brand: 'Aegis AI',
    tagline: 'ಸ್ಮಾರ್ಟ್ ಆರೋಗ್ಯ ಸಂವಹನ ಮತ್ತು ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ',
    need_help: 'ನನಗೆ ಈಗ ಸಹಾಯ ಬೇಕು',
    triage: 'ಟ್ರಯಾಜ್ ಆರಂಭಿಸಿ',
    home: 'ಮುಖಪುಟ',
    continue: 'ಮುಂದೆ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
    mic: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    stop: 'ನಿಲ್ಲಿಸಿ',
    voice_not_supported: 'ಈ ಸಾಧನದಲ್ಲಿ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬೆಂಬಲವಿಲ್ಲ.',
    triage_failed: 'ಟ್ರಯಾಜ್ ವಿಫಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    triage_step_intake: 'ಇನ್‌ಟೇಕ್',
    triage_step_questions: 'ಪ್ರಶ್ನೆಗಳು',
    triage_step_results: 'ಫಲಿತಾಂಶ',
    triage_title: 'ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ',
    triage_helper_title: 'ಹೆಲ್ಪರ್ ಮೋಡ್: ನೀವು ಗಮನಿಸುತ್ತಿರುವುದನ್ನು ವಿವರಿಸಿ',
    triage_helper_text: 'ಸ್ಪಷ್ಟ ವಿವರಗಳು ನೀಡಿ (ಏನು ಸಂಭವಿಸಿತು, ಯಾವಾಗ ಆರಂಭವಾಯಿತು, ಏನು ಬದಲಾಯಿತು).',
    triage_privacy_hint: 'ಅಗತ್ಯವಿಲ್ಲದ ವೈಯಕ್ತಿಕ ವಿವರಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಬೇಡಿ. Aegis ರೋಗನಿರ್ಣಯ/ಔಷಧ ಸೂಚನೆ ನೀಡುವುದಿಲ್ಲ.',
    red_flag_warning: 'ರೆಡ್-ಫ್ಲ್ಯಾಗ ಸೂಚನೆ ಕಂಡುಬಂದಿದೆ. ಇದು ಈಗ ನಡೆಯುತ್ತಿದ್ದರೆ SOS ಬಳಸಿ ಅಥವಾ ತುರ್ತು ಸಂಖ್ಯೆಗೆ ಕರೆಮಾಡಿ.',
    summary: 'ಸಾರಾಂಶ',
    intent: 'ವರ್ಗ',
    open_sos: 'SOS ತೆರೆಯಿರಿ',
    generate_report: 'ವರದಿ ಸೃಷ್ಟಿಸಿ',
    analyze: 'ವಿಶ್ಲೇಷಿಸಿ',
    followups_title: 'ತ್ವರಿತ ಅನುಬಂಧ ಪ್ರಶ್ನೆಗಳು',
    followups_subtitle: 'ಸಂಕ್ಷಿಪ್ತ ಉತ್ತರಗಳು ಸುರಕ್ಷತೆಯನ್ನು ಮೊದಲಿಗಾಗಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ.',
    sos: 'SOS',
    hospitals: 'ಆಸ್ಪತ್ರೆಗಳು',
    reports: 'ವರದಿಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    settings_subtitle: 'ಭಾಷೆ, ಥೀಮ್, ಪ್ರವೇಶಯೋಗ್ಯತೆ, ಪ್ರೊಫೈಲ್, ಸಂಪರ್ಕಗಳು, ಅನುಮತಿಗಳು ಮತ್ತು ಅಲರ್ಟ್‌ಗಳು.',
    language: 'ಭಾಷೆ',
    language_help: 'UI ಭಾಷೆಯನ್ನು ಆರಿಸಿ. ಸುರಕ್ಷತೆ ಮೊದಲ ಆದ್ಯತೆ.',
    theme: 'ಥೀಮ್',
    theme_help: 'ವಿಭಿನ್ನ ಪರಿಸರಗಳಿಗೆ ಕಾಣಿಕೆ ಹೊಂದಿಸಿ.',
    dark: 'ಡಾರ್ಕ್ ಮೋಡ್',
    dark_help: 'ಕಡಿಮೆ ಬೆಳಕಿನಲ್ಲಿ ಬಳಸಲು ಉತ್ತಮ.',
    care_mode: 'ಕೇರ್ ಮೋಡ್ (ದೊಡ್ಡ UI)',
    care_mode_help: 'ಸಂಭಾಳನೆ ಸಂದರ್ಭಗಳಲ್ಲಿ ದೊಡ್ಡ ಪಠ್ಯ ಮತ್ತು ಟ್ಯಾಪ್ ಗಾತ್ರ.',
    my_profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    my_profile_help: 'ತ್ವರಿತ ತುರ್ತು ಹ್ಯಾಂಡಾಫ್‌ಗಾಗಿ ವಿವರಗಳನ್ನು ಸಿದ್ಧವಾಗಿರಿಸಿ.',
    edit_profile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    view_history: 'ಇತಿಹಾಸ ನೋಡಿ',
    privacy_permissions: 'ಗೌಪ್ಯತೆ & ಅನುಮತಿಗಳು',
    privacy_permissions_help: 'ಸ್ಥಳ/ಅಧಿಸೂಚನೆಗಳು ಆಯ್ಕೆಯಾಗಿದೆ; ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಾಯಿಸಬಹುದು.',
    permissions_note:
      'ಸ್ಥಳವನ್ನು ಸಮೀಪದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಲು ಮತ್ತು SOS ಗೆ ನಕ್ಷೆ ಲಿಂಕ್ ಸೇರಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ. ಸ್ಥಳವಿಲ್ಲದೆ ಸಹ ಮುಂದುವರಿಯಬಹುದು, ಆದರೆ ಶಿಫಾರಸುಗಳು ಕಡಿಮೆ ನಿಖರವಾಗಬಹುದು.',
    emergency_contacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    emergency_contacts_help: 'SOS ಅಲರ್ಟ್ ಪಡೆಯುವವರನ್ನು ನಿರ್ವಹಿಸಿ. ಫೋನ್ ಮತ್ತು Telegram ID ಸೇರಿಸಿ.',
    receive_sos: 'SOS ಪಡೆಯಿರಿ',
    add_contact: 'ಸಂಪರ್ಕ ಸೇರಿಸಿ',
    edit_last_contact: 'ಇತ್ತೀಚಿನ ಸಂಪರ್ಕ ತಿದ್ದು',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    relationship: 'ಸಂಬಂಧ',
    relationship_unknown: 'ಸಂಬಂಧ ಸೆಟ್ ಆಗಿಲ್ಲ',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    primary: 'ಪ್ರಮುಖ',
    set_primary: 'ಪ್ರಮುಖವಾಗಿಸಿ',
    remove: 'ತೆಗೆದುಹಾಕಿ',
    unnamed_contact: 'ಹೆಸರಿಲ್ಲದ ಸಂಪರ್ಕ',
    empty_contacts: 'ಇನ್ನೂ ಸಂಪರ್ಕಗಳಿಲ್ಲ. ಕನಿಷ್ಠ ಒಬ್ಬರನ್ನು ಸೇರಿಸಿ.',
    telegram_recipients: 'Telegram ಸ್ವೀಕರಿಸುವವರು',
    telegram_recipients_help: 'ಐಚ್ಛಿಕ: Telegram ಗೆ SOS ಅಲರ್ಟ್ ಕಳುಹಿಸಲು chat ID ಸೇರಿಸಿ.',
    add_telegram: 'Telegram ಸ್ವೀಕರಿಸುವವರು ಸೇರಿಸಿ',
    edit_last_recipient: 'ಇತ್ತೀಚಿನ ಸ್ವೀಕರಿಸುವವರು ತಿದ್ದು',
    unnamed_recipient: 'ಹೆಸರಿಲ್ಲದ ಸ್ವೀಕರಿಸುವವರು',
    empty_telegram: 'ಇನ್ನೂ Telegram ಸ್ವೀಕರಿಸುವವರು ಇಲ್ಲ.',
    telegram_chat_id: 'Telegram chat ID',
    telegram_chat_id_required: 'Telegram chat ID ಅಗತ್ಯ',
    telegram_valid: 'Telegram chat ID ಸರಿಯಾಗಿದೆ.',
    telegram_invalid: 'ಅಮಾನ್ಯ chat ID',
    validate: 'ಪರಿಶೀಲಿಸಿ',
    disclaimer_short:
      'Aegis ರೋಗನಿರ್ಣಯ ಅಥವಾ ಔಷಧ ಸೂಚನೆ ನೀಡುವುದಿಲ್ಲ. ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ನಿಮ್ಮ ಸ್ಥಳೀಯ ತುರ್ತು ಸಂಖ್ಯೆಗೆ ಕರೆಮಾಡಿ.',
    card_chest: 'ಛಾತಿ ನೋವು',
    card_breath: 'ಉಸಿರಾಟ ತೊಂದರೆ',
    card_accident: 'ಅಪಘಾತ',
    card_burn: 'ಸುಡು ಗಾಯ',
    card_poison: 'ವಿಷ ಸೇವನೆ',
    card_fever: 'ಜ್ವರ',
    symptom_placeholder: 'ಏನು ನಡೆಯುತ್ತಿದೆ ಎಂದು ಬರೆಯಿರಿ…',
    voice: 'ಧ್ವನಿ',
    send: 'ಮುಂದೆ',
    risk_low: 'ಕಡಿಮೆ',
    risk_med: 'ಮಧ್ಯಮ',
    risk_high: 'ಹೆಚ್ಚು',
    risk_crit: 'ಗಂಭೀರ',
    why: 'ಈ ಮಟ್ಟ ಏಕೆ?',
    first_aid: 'ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ',
    sos_center: 'SOS ನಿಯಂತ್ರಣ ಕೇಂದ್ರ',
    sos_subtitle: 'ನಿಮ್ಮ ಸಂರಚಿತ ಸ್ವೀಕರಿಸುವವರಿಗೆ ಒಂದೇ ಟ್ಯಾಪ್ ತುರ್ತು ಅಲರ್ಟ್.',
    sos_one_tap: 'ಒಂದೇ-ಟ್ಯಾಪ್ SOS',
    sos_help_text: 'ಸಾರಾಂಶ, ಅಪಾಯ ಮಟ್ಟ, ಸಮಯ ಮತ್ತು (ಲಭ್ಯವಿದ್ದರೆ) ಸ್ಥಳ ಕಳುಹಿಸುತ್ತದೆ.',
    sos_ready: 'ಸಿದ್ಧ. ನಿಜವಾದ ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ಮಾತ್ರ SOS ಒತ್ತಿ.',
    sos_sending: 'ತುರ್ತು ಅಲರ್ಟ್ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…',
    sos_sent: 'ಅಲರ್ಟ್ ಕಳುಹಿಸಲಾಗಿದೆ.',
    sos_failed: 'ಅಲರ್ಟ್ ವಿಫಲ. Telegram ಸ್ವೀಕರಿಸುವವರು/ನೆಟ್‌ವರ್ಕ್ ಪರಿಶೀಲಿಸಿ.',
    sos_recipients: 'ಸ್ವೀಕರಿಸುವವರು',
    copy_emergency_text: 'ತುರ್ತು ಪಠ್ಯ ನಕಲು',
    open_map: 'ನಕ್ಷೆ ತೆರೆಯಿರಿ',
    share_location: 'ಲೈವ್ ಸ್ಥಳ ಹಂಚಿಕೆ',
    copy_report: 'ವರದಿ ನಕಲು',
    home_intro: 'ರಿಯಲ್-ಟೈಮ್ ಆರೋಗ್ಯ ಸಂಪರ್ಕ, ಸ್ಮಾರ್ಟ್ SOS ರೌಟಿಂಗ್ ಮತ್ತು ಲೈವ್ ಆಸ್ಪತ್ರೆ ಶೋಧನೆ.',
    live_gps_tracking: 'ಲೈವ್ GPS ಟ್ರ್ಯಾಕಿಂಗ್',
    ai_triage_enabled: 'AI ಟ್ರಯಾಜ್ ಸಕ್ರಿಯ',
    realtime_alerts: 'ರಿಯಲ್-ಟೈಮ್ ಅಲರ್ಟ್‌ಗಳು',
    hipaa_ready: 'HIPAA ಸಿದ್ಧ',
    live_status: 'ಲೈವ್ ಕಮಾಂಡ್ ಸ್ಥಿತಿ',
    emergency_network_online: 'ತುರ್ತು ಜಾಲ: ಆನ್‌ಲೈನ್',
    risk_score: 'ಅಪಾಯ ಅಂಕೆ',
    triage_level: 'ಟ್ರಯಾಜ್ ಮಟ್ಟ',
    ai_activity_feed: 'AI ಚಟುವಟಿಕೆ ಫೀಡ್',
    ai_activity_feed_desc: 'ವೈಟಲ್‌ಗಳು ಮತ್ತು ಸಮೀಪದ ICU ಲಭ್ಯತೆ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    mini_live_map_preview: 'ಮಿನಿ ಲೈವ್ ಮ್ಯಾಪ್ • ಸಮೀಪದಲ್ಲಿ 3 ಪ್ರತಿಕ್ರಿಯಾಕಾರರು',
    emergency_action_grid: 'ತುರ್ತು ಕ್ರಿಯಾ ಗ್ರಿಡ್',
    quick_intake_prompts: 'ತ್ವರಿತ ಇನ್‌ಟೇಕ್ ಪ್ರಾಂಪ್ಟ್‌ಗಳು',
    quick_intake_subtitle: 'ಸಾಮಾನ್ಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿಗೆ ಒಂದು ಟ್ಯಾಪ್‌ನಲ್ಲಿ ಟ್ರಯಾಜ್ ಪ್ರಾರಂಭಿಸಿ.',
    live_map_hospitals: 'ಲೈವ್ ಮ್ಯಾಪ್ + ಆಸ್ಪತ್ರೆಗಳು',
    realtime_routes_markers: 'ರಿಯಲ್-ಟೈಮ್ ಮಾರ್ಗಗಳು ಮತ್ತು ಗುರುತುಗಳು',
    map_unavailable: 'ನಕ್ಷೆ ಲಭ್ಯವಿಲ್ಲ',
    no_nearby_hospitals_loaded: 'ಸಮೀಪದ ಆಸ್ಪತ್ರೆಗಳು ಲೋಡ್ ಆಗಿಲ್ಲ.',
    system_feed: 'ಸಿಸ್ಟಮ್ ಫೀಡ್',
    last_updated: 'ಕೊನೆಯ ನವೀಕರಣ',
    not_synced_yet: 'ಇನ್ನೂ ಸಿಂಕ್ ಆಗಿಲ್ಲ',
    refreshing_location_hospitals: 'ಸ್ಥಳ ಮತ್ತು ಆಸ್ಪತ್ರೆಗಳನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡುತ್ತಿದೆ...',
    location_hospital_sync_complete: 'ಸ್ಥಳ ಮತ್ತು ಆಸ್ಪತ್ರೆ ಸಿಂಕ್ ಪೂರ್ಣಗೊಂಡಿದೆ.',
    no_active_emergency_timeline: 'ಸಕ್ರಿಯ ತುರ್ತು ಟೈಮ್‌ಲೈನ್ ಇಲ್ಲ. ಲೈವ್ ಪ್ರಕರಣಕ್ಕೆ ಟ್ರಯಾಜ್ ಪ್ರಾರಂಭಿಸಿ.',
    location_status: 'ಸ್ಥಳ ಸ್ಥಿತಿ',
    available: 'ಲಭ್ಯ',
    pending: 'ಬಾಕಿ',
    awaiting: 'ಕಾಯುತ್ತಿದೆ',
    response_mode: 'ಪ್ರತಿಕ್ರಿಯೆ ಮೋಡ್',
    bystander_mode: 'ಇತರರಿಗೆ ಸಹಾಯ',
    self_mode: 'ಸ್ವಯಂ ಕಾಳಜಿ',
    network: 'ಜಾಲ',
    online: 'ಆನ್‌ಲೈನ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    stable: 'ಸ್ಥಿರ',
    check: 'ಪರಿಶೀಲಿಸಿ',
    syncing: 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ',
    live: 'ಲೈವ್',
    user: 'ಬಳಕೆದಾರ',
    prompt_chest_sweat: 'ಛಾತಿ ನೋವು ಮತ್ತು ಬೆವರು',
    prompt_unconscious: 'ಅಚೇತನ ರೋಗಿ',
    prompt_breathing_difficulty: 'ತೀವ್ರ ಉಸಿರಾಟ ತೊಂದರೆ',
    prompt_heavy_bleeding: 'ಅಪಘಾತದ ನಂತರ ಹೆಚ್ಚಿನ ರಕ್ತಸ್ರಾವ',
    beds: 'ಹಾಸಿಗೆಗಳು',
    eta: 'ETA',
    nearby: 'ಸಮೀಪ',
    badge_critical: 'ಗಂಭೀರ',
    badge_high: 'ಹೆಚ್ಚು',
    badge_moderate: 'ಮಧ್ಯಮ',
    cardiac_arrest: 'ಹೃದಯ ಸ್ಥಂಭನ',
    cardiac_desc: 'ತಕ್ಷಣದ CPR ಮತ್ತು ಆದ್ಯತೆಯ ಡಿಸ್ಪ್ಯಾಚ್ ಕಾರ್ಯಪ್ರವಾಹ.',
    breathing_issues: 'ಉಸಿರಾಟ ಸಮಸ್ಯೆ',
    breathing_desc: 'ವಾಯುಮಾರ್ಗ ಅಪಾಯ ಪತ್ತೆ ಮತ್ತು ವೇಗದ ಟ್ರಯಾಜ್ ಮಾರ್ಗೀಕರಣ.',
    accident_trauma: 'ಅಪಘಾತ ಟ್ರಾಮಾ',
    trauma_desc: 'ಬಹು ಗಾಯ ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ಏರಿಕೆ ಪ್ರೋಟೋಕಾಲ್.',
    burn_injury: 'ಸುಡು ಗಾಯ',
    burn_desc: 'ತೀವ್ರತೆ ಆಧಾರಿತ ಸುಡು ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ.',
    poisoning_title: 'ವಿಷಪೂರಿತತೆ',
    poisoning_desc: 'ವಿಷಕಾರಿ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಸೇವನೆ ಮಾರ್ಗದರ್ಶನ.',
    high_fever: 'ಹೆಚ್ಚಿನ ಜ್ವರ',
    high_fever_desc: 'ಅಪಾಯ ಸೂಚನೆಗಳ ಪರಿಶೀಲನೆ ಮತ್ತು ಕಾಳಜಿ ಶಿಫಾರಸುಗಳು.',
    stroke_title: 'ಪಕ್ಷಾಘಾತ',
    stroke_desc: 'FAST ಲಕ್ಷಣ ಪರಿಶೀಲನೆ ಮತ್ತು ಗೋಲ್ಡನ್-ಆವರ್ ಸಮನ್ವಯ.',
    mental_health_crisis: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ ಸಂಕಟ',
    mental_health_desc: 'ಸಂಕಟ-ಸುರಕ್ಷಿತ ಹಸ್ತಕ್ಷೇಪ ಮತ್ತು ತ್ವರಿತ ಸಹಾಯ ಮಾರ್ಗೀಕರಣ.',
    setup_checklist: 'ನಿಮ್ಮ ತುರ್ತು ಸಿದ್ಧತೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ',
    setup_checklist_hint: 'SOS ಸಂಪೂರ್ಣ ಸಿದ್ಧವಾಗಲು ಪ್ರೊಫೈಲ್ ಮತ್ತು ಕನಿಷ್ಠ ಒಂದು ಸಂಪರ್ಕ ಸೇರಿಸಿ.',
    dismiss: 'ಮುಚ್ಚಿ',
    report_empty_hint: 'ಮೊದಲು ಟ್ರಯಾಜ್ ಮಾಡಿ, ನಂತರ ವೈದ್ಯಕೀಯ ವರದಿ ರಚಿಸಿ.',
    accessibility: 'ಪ್ರವೇಶಯೋಗ್ಯತೆ',
    accessibility_help: 'ಓದಬಹುದಾಗುವಿಕೆ ಮತ್ತು ಬಳಕೆ ಸೌಕರ್ಯ ಹೆಚ್ಚಿಸಿ.',
    large_text: 'ದೊಡ್ಡ ಪಠ್ಯ',
    reduce_motion: 'ಕಡಿಮೆ ಚಲನೆ',
    high_contrast: 'ಉನ್ನತ ಕಾಂಟ್ರಾಸ್ಟ್',
    notification_preferences: 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    notification_preferences_help: 'ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿನ ಅಲರ್ಟ್ ವರ್ತನೆ ನಿಯಂತ್ರಿಸಿ.',
    quiet_mode: 'ಶಾಂತ ಮೋಡ್',
    vibration: 'ವೈಬ್ರೇಶನ್',
    quick_edit: 'ಹೊಸ ಎಂಟ್ರಿ ತ್ವರಿತ ಸಂಪಾದನೆ',
    invalid_phone: 'ಅಮಾನ್ಯ ಫೋನ್ ಮಾದರಿ',
    bystander: 'ನಾನು ಇನ್ನೊಬ್ಬರಿಗೆ ಸಹಾಯ ಮಾಡುತ್ತಿದ್ದೇನೆ',
  },
  zh: {
    nearby_facilities: '附近医疗机构',
    hospitals_realtime_caption: '允许定位后可获取实时附近医院。',
    hospitals_fetch_error: '无法获取定位，医院列表加载失败。',
    hospitals_fallback_notice: '定位不可用，正在显示默认附近区域的医院。',
    hospitals_load_failed: '医院加载失败',
    no_facilities_found: '未找到机构',
    check_location_and_retry: '请检查定位权限后重试。',
    medical: '医疗',
    try_again: '重试',
    back_to_triage: '返回分诊',
    location_prefix: '定位',
    location_active: '已启用',
    location_not_granted: '未授权',
    telegram_delivery_failed: 'Telegram 发送失败',
    sos_triggered: '已触发 SOS',
    manual_sos: '手动 SOS',
    incident_history_title: '事件历史',
    history_load_error: '历史记录加载失败（后端是否已启动？）',
    no_incidents: '暂无服务端事件记录。',
    profile_page_title: '家庭与紧急档案',
    profile_page_caption: '用于上下文与 SOS 联系人信息。',
    saving: '保存中…',
    save_success: '本次会话已安全保存。',
    save_local: '仅本地保存。',
    name_label: '姓名',
    age_label: '年龄',
    allergies_label: '过敏史（逗号分隔）',
    contacts_phone_label: '紧急联系人电话（逗号分隔）',
    notes_label: '备注',
    save_profile: '保存档案',
    report_title: '急诊交接报告',
    report_requires_triage: '请先完成分诊以生成完整报告。',
    generate_handoff: '生成交接文档',
    generating: '生成中…',
    download_pdf: '下载 PDF',
    brand: 'Aegis AI',
    tagline: '智能医疗沟通与紧急响应',
    need_help: '我现在需要帮助',
    triage: '开始分诊',
    home: '首页',
    continue: '继续',
    analyzing: '分析中…',
    mic: '语音输入',
    stop: '停止',
    voice_not_supported: '此设备不支持语音输入。',
    triage_failed: '分诊失败，请重试。',
    triage_step_intake: '信息',
    triage_step_questions: '问题',
    triage_step_results: '结果',
    triage_title: '描述症状',
    triage_helper_title: '协助模式：描述你观察到的情况',
    triage_helper_text: '请提供清晰事实（发生了什么、何时开始、有什么变化）。',
    triage_privacy_hint: '避免分享不必要的个人信息。本工具不诊断或开处方。',
    red_flag_warning: '检测到危险信号用语。如正在发生，请使用 SOS 或拨打当地急救电话。',
    summary: '摘要',
    intent: '类别',
    open_sos: '打开 SOS',
    generate_report: '生成报告',
    analyze: '分析',
    followups_title: '快速追问',
    followups_subtitle: '简短回答有助于优先保障安全。',
    sos: 'SOS',
    hospitals: '医院',
    reports: '报告',
    settings: '设置',
    settings_subtitle: '语言、主题、无障碍、档案、联系人、权限与警报。',
    language: '语言',
    language_help: '选择界面语言。安全优先，内容保持一致。',
    theme: '主题',
    theme_help: '根据环境调整显示。',
    dark: '深色模式',
    dark_help: '建议在弱光环境使用。',
    care_mode: '关怀模式（更大界面）',
    care_mode_help: '更大的文字与触控区域，适合照护场景。',
    my_profile: '我的档案',
    my_profile_help: '准备好信息，以便紧急情况快速交接。',
    edit_profile: '编辑档案',
    view_history: '查看历史',
    privacy_permissions: '隐私与权限',
    privacy_permissions_help: '定位/通知为可选，随时可更改。',
    permissions_note:
      '定位用于查找附近医院并在 SOS 中添加地图链接。你也可以不启用定位继续使用，但推荐可能不够精确。',
    emergency_contacts: '紧急联系人',
    emergency_contacts_help: '管理谁会收到 SOS 警报。可添加电话与 Telegram ID。',
    receive_sos: '接收 SOS',
    add_contact: '添加联系人',
    edit_last_contact: '编辑最近联系人',
    full_name: '姓名',
    relationship: '关系',
    relationship_unknown: '未设置关系',
    phone: '电话',
    primary: '主要',
    set_primary: '设为主要',
    remove: '移除',
    unnamed_contact: '未命名联系人',
    empty_contacts: '暂无紧急联系人。建议至少添加一位可信任的人。',
    telegram_recipients: 'Telegram 接收者',
    telegram_recipients_help: '可选：添加 Telegram chat ID 以接收服务器发送的 SOS。',
    add_telegram: '添加 Telegram 接收者',
    edit_last_recipient: '编辑最近接收者',
    unnamed_recipient: '未命名接收者',
    empty_telegram: '暂无 Telegram 接收者。',
    telegram_chat_id: 'Telegram chat ID',
    telegram_chat_id_required: '需要 Telegram chat ID',
    telegram_valid: 'chat ID 看起来有效。',
    telegram_invalid: '无效的 chat ID',
    validate: '验证',
    disclaimer_short: 'Aegis 不进行诊断或开具处方。紧急情况下请拨打当地急救电话。',
    card_chest: '胸痛',
    card_breath: '呼吸困难',
    card_accident: '事故',
    card_burn: '烧伤',
    card_poison: '中毒',
    card_fever: '发热',
    symptom_placeholder: '请描述正在发生什么…',
    voice: '语音',
    send: '继续',
    risk_low: '低',
    risk_med: '中',
    risk_high: '高',
    risk_crit: '危急',
    why: '为什么是这个等级？',
    first_aid: '急救',
    sos_center: 'SOS 控制中心',
    sos_subtitle: '一键向已配置的接收者发送紧急警报。',
    sos_one_tap: '一键 SOS',
    sos_help_text: '发送患者摘要、紧急程度、时间与（如可用）位置。',
    sos_ready: '就绪。仅在真实紧急情况点击 SOS。',
    sos_sending: '正在发送紧急警报…',
    sos_sent: '已发送警报。',
    sos_failed: '发送失败。请检查 Telegram 接收者与网络。',
    sos_recipients: '接收者',
    copy_emergency_text: '复制紧急文本',
    open_map: '打开地图',
    share_location: '共享实时位置',
    copy_report: '复制报告',
    home_intro: '实时医疗沟通、智能 SOS 路由与附近医院发现。',
    live_gps_tracking: '实时 GPS 追踪',
    ai_triage_enabled: 'AI 分诊已启用',
    realtime_alerts: '实时警报',
    hipaa_ready: 'HIPAA 就绪',
    live_status: '实时指挥状态',
    emergency_network_online: '紧急网络：在线',
    risk_score: '风险评分',
    triage_level: '分诊等级',
    ai_activity_feed: 'AI 活动流',
    ai_activity_feed_desc: '正在分析生命体征和附近 ICU 可用性...',
    mini_live_map_preview: '迷你实时地图预览 • 附近 3 名响应者',
    emergency_action_grid: '紧急操作网格',
    quick_intake_prompts: '快速输入提示',
    quick_intake_subtitle: '一键开始常见紧急情况分诊。',
    live_map_hospitals: '实时地图 + 医院',
    realtime_routes_markers: '实时路线与标记',
    map_unavailable: '地图不可用',
    no_nearby_hospitals_loaded: '附近医院尚未加载。',
    system_feed: '系统动态',
    last_updated: '最后更新',
    not_synced_yet: '尚未同步',
    refreshing_location_hospitals: '正在刷新位置和医院...',
    location_hospital_sync_complete: '位置与医院同步完成。',
    no_active_emergency_timeline: '暂无活动紧急时间线。先开始分诊创建病例。',
    location_status: '位置状态',
    available: '可用',
    pending: '等待中',
    awaiting: '等待',
    response_mode: '响应模式',
    bystander_mode: '帮助他人',
    self_mode: '自我护理',
    network: '网络',
    online: '在线',
    offline: '离线',
    stable: '稳定',
    check: '检查',
    syncing: '同步中',
    live: '实时',
    user: '用户',
    prompt_chest_sweat: '胸痛并出汗',
    prompt_unconscious: '患者昏迷',
    prompt_breathing_difficulty: '严重呼吸困难',
    prompt_heavy_bleeding: '事故后大量出血',
    beds: '床位',
    eta: '预计到达',
    nearby: '附近',
    badge_critical: '危急',
    badge_high: '高',
    badge_moderate: '中',
    cardiac_arrest: '心脏骤停',
    cardiac_desc: '立即 CPR 与优先调度流程。',
    breathing_issues: '呼吸问题',
    breathing_desc: '气道风险识别与快速分诊路由。',
    accident_trauma: '事故创伤',
    trauma_desc: '多发伤评估与升级处理流程。',
    burn_injury: '烧伤',
    burn_desc: '基于严重程度的烧伤应急响应。',
    poisoning_title: '中毒',
    poisoning_desc: '毒性响应与摄入指导流程。',
    high_fever: '高热',
    high_fever_desc: '危险信号筛查与护理建议。',
    stroke_title: '卒中',
    stroke_desc: 'FAST 症状检查与黄金时间协同。',
    mental_health_crisis: '心理健康危机',
    mental_health_desc: '危机安全干预与紧急支持路由。',
    setup_checklist: '完成紧急设置',
    setup_checklist_hint: '添加档案和至少一位紧急联系人，让 SOS 完全可用。',
    dismiss: '关闭',
    report_empty_hint: '请先完成分诊，再生成临床可读报告。',
    accessibility: '无障碍',
    accessibility_help: '提升可读性与操作舒适度。',
    large_text: '大字体',
    reduce_motion: '减少动画',
    high_contrast: '高对比度',
    notification_preferences: '通知偏好',
    notification_preferences_help: '控制紧急情况下的提醒行为。',
    quiet_mode: '静音模式',
    vibration: '震动',
    quick_edit: '快速编辑最新条目',
    invalid_phone: '电话号码格式无效',
    bystander: '我在帮助他人',
  },
  ja: {
    nearby_facilities: '近くの医療施設',
    hospitals_realtime_caption: '位置情報が許可されると近隣病院をリアルタイム取得します。',
    hospitals_fetch_error: '位置情報が利用できず、病院一覧を取得できませんでした。',
    hospitals_fallback_notice: '位置情報が利用できないため、既定の近隣エリアの病院を表示しています。',
    hospitals_load_failed: '病院を読み込めませんでした',
    no_facilities_found: '施設が見つかりません',
    check_location_and_retry: '位置情報の許可を確認して再試行してください。',
    medical: '医療',
    try_again: '再試行',
    back_to_triage: 'トリアージに戻る',
    location_prefix: '位置情報',
    location_active: '有効',
    location_not_granted: '未許可',
    telegram_delivery_failed: 'Telegram 配信に失敗しました',
    sos_triggered: 'SOS を送信しました',
    manual_sos: '手動 SOS',
    incident_history_title: 'インシデント履歴',
    history_load_error: '履歴を読み込めませんでした（バックエンドは起動中ですか？）',
    no_incidents: 'サーバー側の記録はまだありません。',
    profile_page_title: '家族と緊急プロフィール',
    profile_page_caption: 'コンテキストと SOS 連絡先に使用されます。',
    saving: '保存中…',
    save_success: 'このセッションに安全に保存しました。',
    save_local: 'ローカルにのみ保存しました。',
    name_label: '名前',
    age_label: '年齢',
    allergies_label: 'アレルギー（カンマ区切り）',
    contacts_phone_label: '緊急連絡先（電話、カンマ区切り）',
    notes_label: 'メモ',
    save_profile: 'プロフィールを保存',
    report_title: '緊急レポート',
    report_requires_triage: '完全なレポートのために先にトリアージを実行してください。',
    generate_handoff: '引き継ぎ文書を生成',
    generating: '生成中…',
    download_pdf: 'PDF をダウンロード',
    brand: 'Aegis AI',
    tagline: '医療コミュニケーションと緊急対応',
    need_help: '今すぐ助けが必要',
    triage: 'トリアージ開始',
    home: 'ホーム',
    continue: '続行',
    analyzing: '解析中…',
    mic: '音声入力',
    stop: '停止',
    voice_not_supported: 'この端末は音声入力に対応していません。',
    triage_failed: 'トリアージに失敗しました。もう一度お試しください。',
    triage_step_intake: '入力',
    triage_step_questions: '質問',
    triage_step_results: '結果',
    triage_title: '症状を説明してください',
    triage_helper_title: '介助モード：観察した内容を説明してください',
    triage_helper_text: '事実ベースで（何が起きたか・いつからか・変化）を入力してください。',
    triage_privacy_hint: '不要な個人情報は入力しないでください。診断や処方は行いません。',
    red_flag_warning: '危険な表現を検出しました。今起きている場合は SOS または地域の緊急番号へ。',
    summary: '要約',
    intent: '分類',
    open_sos: 'SOS を開く',
    generate_report: 'レポート作成',
    analyze: '解析',
    followups_title: '追加の確認質問',
    followups_subtitle: '短い回答が安全性の優先判断に役立ちます。',
    sos: 'SOS',
    hospitals: '病院',
    reports: 'レポート',
    settings: '設定',
    settings_subtitle: '言語、テーマ、アクセシビリティ、プロフィール、連絡先、権限、アラート。',
    language: '言語',
    language_help: 'UI 言語を選択します。安全第一で一貫性を保ちます。',
    theme: 'テーマ',
    theme_help: '環境に合わせて表示を調整します。',
    dark: 'ダークモード',
    dark_help: '暗い場所での使用に推奨。',
    care_mode: 'ケアモード（大きい UI）',
    care_mode_help: '介助時に読みやすい文字と大きいタップ領域。',
    my_profile: 'プロフィール',
    my_profile_help: '緊急時の引き継ぎに備えて情報を整えます。',
    edit_profile: 'プロフィール編集',
    view_history: '履歴を見る',
    privacy_permissions: 'プライバシーと権限',
    privacy_permissions_help: '位置情報/通知は任意で、いつでも変更できます。',
    permissions_note:
      '位置情報は近くの病院検索と SOS の地図リンクに使用します。位置情報なしでも利用できますが、提案の精度が下がる場合があります。',
    emergency_contacts: '緊急連絡先',
    emergency_contacts_help: 'SOS を受け取る相手を管理します。電話番号と Telegram ID を追加できます。',
    receive_sos: 'SOS を受け取る',
    add_contact: '連絡先を追加',
    edit_last_contact: '最新の連絡先を編集',
    full_name: '氏名',
    relationship: '関係',
    relationship_unknown: '関係未設定',
    phone: '電話番号',
    primary: '主要',
    set_primary: '主要に設定',
    remove: '削除',
    unnamed_contact: '名前なし連絡先',
    empty_contacts: '緊急連絡先がありません。信頼できる人を少なくとも1名追加してください。',
    telegram_recipients: 'Telegram 送信先',
    telegram_recipients_help: '任意：Telegram chat ID を追加してサーバーから SOS を送信します。',
    add_telegram: 'Telegram 送信先を追加',
    edit_last_recipient: '最新の送信先を編集',
    unnamed_recipient: '名前なし送信先',
    empty_telegram: 'Telegram 送信先がありません。',
    telegram_chat_id: 'Telegram chat ID',
    telegram_chat_id_required: 'Telegram chat ID が必要です',
    telegram_valid: 'chat ID は有効そうです。',
    telegram_invalid: '無効な chat ID',
    validate: '確認',
    disclaimer_short: 'Aegis は診断や処方を行いません。緊急時は地域の緊急番号に連絡してください。',
    card_chest: '胸の痛み',
    card_breath: '呼吸困難',
    card_accident: '事故',
    card_burn: 'やけど',
    card_poison: '中毒',
    card_fever: '発熱',
    symptom_placeholder: '状況を説明してください…',
    voice: '音声',
    send: '続行',
    risk_low: '低',
    risk_med: '中',
    risk_high: '高',
    risk_crit: '危機的',
    why: 'このレベルの理由',
    first_aid: '応急処置',
    sos_center: 'SOS コントロールセンター',
    sos_subtitle: '設定した送信先へワンタップで緊急アラートを送信します。',
    sos_one_tap: 'ワンタップ SOS',
    sos_help_text: '要約、緊急度、時刻、（可能なら）位置情報を送信します。',
    sos_ready: '準備完了。緊急時のみ SOS を押してください。',
    sos_sending: '緊急アラート送信中…',
    sos_sent: '送信しました。',
    sos_failed: '送信失敗。Telegram 送信先とネットワークを確認してください。',
    sos_recipients: '送信先',
    copy_emergency_text: '緊急テキストをコピー',
    open_map: '地図を開く',
    share_location: '位置情報を共有',
    copy_report: 'レポートをコピー',
    home_intro: 'リアルタイム医療コミュニケーション、スマート SOS 連携、近隣病院検索。',
    live_gps_tracking: 'ライブ GPS 追跡',
    ai_triage_enabled: 'AI トリアージ有効',
    realtime_alerts: 'リアルタイムアラート',
    hipaa_ready: 'HIPAA 対応',
    live_status: 'ライブ指揮ステータス',
    emergency_network_online: '緊急ネットワーク: オンライン',
    risk_score: 'リスクスコア',
    triage_level: 'トリアージレベル',
    ai_activity_feed: 'AI アクティビティフィード',
    ai_activity_feed_desc: 'バイタルと近隣 ICU 空き状況を解析中...',
    mini_live_map_preview: 'ミニライブマップ • 近くに3名の対応者',
    emergency_action_grid: '緊急アクショングリッド',
    quick_intake_prompts: 'クイック入力プロンプト',
    quick_intake_subtitle: 'ワンタップで一般的な緊急ケースのトリアージを開始。',
    live_map_hospitals: 'ライブマップ + 病院',
    realtime_routes_markers: 'リアルタイム経路とマーカー',
    map_unavailable: '地図を表示できません',
    no_nearby_hospitals_loaded: '近隣病院を読み込めませんでした。',
    system_feed: 'システムフィード',
    last_updated: '最終更新',
    not_synced_yet: '未同期',
    refreshing_location_hospitals: '位置情報と病院を更新中...',
    location_hospital_sync_complete: '位置情報と病院の同期が完了しました。',
    no_active_emergency_timeline: 'アクティブな緊急タイムラインはありません。トリアージを開始してください。',
    location_status: '位置情報ステータス',
    available: '利用可能',
    pending: '保留中',
    awaiting: '待機中',
    response_mode: '対応モード',
    bystander_mode: '他者を支援',
    self_mode: '自己ケア',
    network: 'ネットワーク',
    online: 'オンライン',
    offline: 'オフライン',
    stable: '安定',
    check: '確認',
    syncing: '同期中',
    live: 'ライブ',
    user: 'ユーザー',
    prompt_chest_sweat: '胸痛と発汗',
    prompt_unconscious: '意識不明の患者',
    prompt_breathing_difficulty: '重度の呼吸困難',
    prompt_heavy_bleeding: '事故後の大量出血',
    beds: '病床',
    eta: '到着目安',
    nearby: '近隣',
    badge_critical: '危機的',
    badge_high: '高',
    badge_moderate: '中',
    cardiac_arrest: '心停止',
    cardiac_desc: '即時 CPR と優先ディスパッチ手順。',
    breathing_issues: '呼吸問題',
    breathing_desc: '気道リスク検出と迅速なトリアージ誘導。',
    accident_trauma: '事故外傷',
    trauma_desc: '多発外傷評価とエスカレーション手順。',
    burn_injury: '熱傷',
    burn_desc: '重症度に応じた熱傷緊急対応。',
    poisoning_title: '中毒',
    poisoning_desc: '毒性対応と摂取時ガイダンス。',
    high_fever: '高熱',
    high_fever_desc: '危険サインのスクリーニングとケア推奨。',
    stroke_title: '脳卒中',
    stroke_desc: 'FAST 症状確認とゴールデンアワー連携。',
    mental_health_crisis: 'メンタルヘルス危機',
    mental_health_desc: '危機時の安全介入と緊急支援ルーティング。',
    setup_checklist: '緊急セットアップを完了',
    setup_checklist_hint: 'プロフィールと最低1件の緊急連絡先を追加して SOS を有効化します。',
    dismiss: '閉じる',
    report_empty_hint: '先にトリアージを実行してからレポートを生成してください。',
    accessibility: 'アクセシビリティ',
    accessibility_help: '読みやすさと操作しやすさを改善します。',
    large_text: '大きな文字',
    reduce_motion: 'モーションを減らす',
    high_contrast: '高コントラスト',
    notification_preferences: '通知設定',
    notification_preferences_help: '緊急時の通知動作を制御します。',
    quiet_mode: 'サイレントモード',
    vibration: 'バイブレーション',
    quick_edit: '最新項目をクイック編集',
    invalid_phone: '電話番号の形式が無効です',
    bystander: '他の人を助けています',
  },
};
